In [17]:
pip install pymysql

Requirement already satisfied: pymysql in c:\users\abhay\anaconda3\lib\site-packages (1.1.1)
Note: you may need to restart the kernel to use updated packages.

In [18]:
from sqlalchemy import create_engine
import pandas as pd

In [19]:
df = pd.read_csv("deepseek_vs_chatgpt.csv")
df.head()

,Date,Month_Num,Weekday,AI_Platform,AI_Model_Version,Active_Users,New_Users,Churned_Users,Daily_Churn_Rate,Retention_Rate,...,Session_Duration_sec,Device_Type,Language,Response_Accuracy,Response_Speed_sec,Response_Time_Category,Correction_Needed,User_Return_Frequency,Customer_Support_Interactions,Region
0,2024-09-21,9,Saturday,ChatGPT,GPT-4-turbo,500000,25000,25000,0.05,0.95,...,40,Mobile,es,0.7842,3.30,Standard,0,6,2,Antarctica (the territory South of 60 deg S)
1,2024-09-21,9,Saturday,ChatGPT,GPT-4-turbo,500000,25000,25000,0.05,0.95,...,24,Laptop/Desktop,zh,0.8194,3.28,Standard,1,2,2,Ukraine
2,2024-09-21,9,Saturday,ChatGPT,GPT-4-turbo,500000,25000,25000,0.05,0.95,...,34,Mobile,en,0.8090,3.07,Standard,0,2,0,Grenada
3,2024-09-21,9,Saturday,ChatGPT,GPT-4-turbo,500000,25000,25000,0.05,0.95,...,18,Mobile,fr,0.8233,3.06,Standard,0,9,0,Guyana
4,2024-05-16,5,Thursday,DeepSeek,DeepSeek-Chat 1.5,1700000,170000,34000,0.02,0.95,...,10,Mobile,de,0.9366,1.48,Fast,0,9,3,India

In [20]:
df.shape

(10000, 28)

In [29]:
engine = create_engine("mysql+pymysql://student:@localhost:3306/ai_comparison_db")
df.to_sql("deepseek_vs_chatgpt",con=engine,index=False,if_exists='replace')

10000

In [31]:
df=pd.read_sql("select * from deepseek_vs_chatgpt",con=engine)
print(df)

            Date  Month_Num   Weekday AI_Platform   AI_Model_Version  \
0     2024-09-21          9  Saturday     ChatGPT        GPT-4-turbo
1     2024-09-21          9  Saturday     ChatGPT        GPT-4-turbo
2     2024-09-21          9  Saturday     ChatGPT        GPT-4-turbo
3     2024-09-21          9  Saturday     ChatGPT        GPT-4-turbo
4     2024-05-16          5  Thursday    DeepSeek  DeepSeek-Chat 1.5
...          ...        ...       ...         ...                ...
9995  2024-05-17          5    Friday    DeepSeek  DeepSeek-Chat 1.5
9996  2024-05-17          5    Friday    DeepSeek  DeepSeek-Chat 1.5
9997  2024-05-17          5    Friday    DeepSeek  DeepSeek-Chat 1.5
9998  2024-05-17          5    Friday    DeepSeek  DeepSeek-Chat 1.5
9999  2024-05-17          5    Friday    DeepSeek  DeepSeek-Chat 1.5

      Active_Users  New_Users  Churned_Users  Daily_Churn_Rate  \
0           500000      25000          25000              0.05
1           500000      25000          25000              0.05
2           500000      25000          25000              0.05
3           500000      25000          25000              0.05
4          1700000     170000          34000              0.02
...            ...        ...            ...               ...
9995       1700000     170000          34000              0.02
9996       1700000     170000          34000              0.02
9997       1700000     170000          34000              0.02
9998       1700000     170000          34000              0.02
9999       1700000     170000          34000              0.02

      Retention_Rate  ... Session_Duration_sec     Device_Type Language  \
0               0.95  ...                   40          Mobile       es
1               0.95  ...                   24  Laptop/Desktop       zh
2               0.95  ...                   34          Mobile       en
3               0.95  ...                   18          Mobile       fr
4               0.95  ...                   10          Mobile       de
...              ...  ...                  ...             ...      ...
9995            0.95  ...                   34  Laptop/Desktop       zh
9996            0.95  ...                   19  Laptop/Desktop       en
9997            0.95  ...                   29  Laptop/Desktop       de
9998            0.95  ...                   21          Mobile       de
9999            0.95  ...                   58          Mobile       fr

      Response_Accuracy  Response_Speed_sec Response_Time_Category  \
0                0.7842                3.30               Standard
1                0.8194                3.28               Standard
2                0.8090                3.07               Standard
3                0.8233                3.06               Standard
4                0.9366                1.48                   Fast
...                 ...                 ...                    ...
9995             0.9791                0.60                Instant
9996             0.9132                0.83                Instant
9997             0.9516                0.94                Instant
9998             0.9359                0.83                Instant
9999             0.9399                0.76                Instant

      Correction_Needed  User_Return_Frequency  Customer_Support_Interactions  \
0                     0                      6                              2
1                     1                      2                              2
2                     0                      2                              0
3                     0                      9                              0
4                     0                      9                              3
...                 ...                    ...                            ...
9995                  0                      7                              2
9996                  0                      5                              0
9997                  0                     10                              2
9998                  0                      5                              3
9999                  1                      7                              1

                                            Region
0     Antarctica (the territory South of 60 deg S)
1                                          Ukraine
2                                          Grenada
3                                           Guyana
4                                            India
...                                            ...
9995                                    Seychelles
9996                              Christmas Island
9997                                      Ethiopia
9998                                   Puerto Rico
9999                               Kyrgyz Republic

[10000 rows x 28 columns]